name: Create test build

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Which branch to build"
        default: "main"
        required: true
        type: string
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ inputs.branch }}"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.82.0

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install NPM dependencies
        run: pnpm install

      - name: Build & Bundle
        run: pnpm build
        env:
          RUSTFLAGS: --cfg getrandom_backend="wasm_js"

      - name: Pack
        run: npm pack --pack-destination ~

      - uses: actions/upload-artifact@v4
        with:
          name: packed
          path: "~/*.tgz"
